version: '3.12'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
    command: uvicorn src.api.app:app --host 0.0.0.0 --port 8000
